version: '3.4'

# defined manually
services:
  catalogdb:
    image: mongo
  
  basketdb:
    image: redis:alpine  #alpine is light version of redis 
   
  discountdb:
    image: postgres

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

#defined manually
volumes:
  mongo_data:
  portainer_data:
  postgres_data:
